[package]
name = "zydis-wasm"
version = "0.1.0"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
zydis = { git = "https://github.com/zyantific/zydis-rs", branch="webassembly", features=["wasm"]}